on:
  workflow_call:
    inputs:
      service:
        type: string
        default: ${{ github.event.repository.name }}
      env:
        type: string
        required: true
    secrets:
      PAT:
        required: true
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: third-place/platform
          ref: main
          token: ${{ secrets.PAT }}
      - run: sudo snap install yq
      - run: yq -i '.versions.${{ inputs.service }}.version = "${{ github.sha }}"' registry/versions.${{ inputs.env }}.yaml
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: Update deployed version for ${{ inputs.service }}
