on:
  workflow_call:
    inputs:
      service_name:
        type: string
        default: ${{ github.event.repository.name }}
    secrets:
      PAT:
        required: true
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: third-place/platform
          ref: main
          token: ${{ secrets.PAT }}
      - run: sudo snap install yq
      - run: yq -i '.global.versions.${{ inputs.service_name }}.version = "${{ github.sha }}"' env/dev/values.yaml
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: Update deployed version for ${{ inputs.service_name }}
