on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      env:
        required: true
        type: string
    secrets:
      ACTIONS_CHECKOUT_PAT:
        required: true
jobs:
  deploy-to-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.ACTIONS_CHECKOUT_PAT }}
      - run: sudo snap install yq
      - run: yq -i '.spec.template.spec.containers[0].image = "ghcr.io/${{ github.repository }}:${{ inputs.tag }}"' kustomize/prod/deployment.yaml
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: "Deploy version ${{ inputs.tag }} to ${{ inputs.env }}"
