on:
  workflow_call:
    inputs:
      service:
        type: string
        default: ${{ github.event.repository.name }}
      env:
        type: string
        required: true
    secrets:
      PAT:
        required: true
      KUBE_CONFIG:
        required: true
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: third-place/platform
          ref: main
          token: ${{ secrets.PAT }}
      - run: sudo snap install yq
      - run: yq -i '.global.versions.${{ inputs.service }}.version = "${{ github.sha }}"' env/${{ inputs.env }}/values.yaml
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: Update deployed version for ${{ inputs.service }}
      - uses: azure/setup-helm@v4.1.0
      - uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm dependency build env/${{ inputs.env }}
          kubeconfig: '${{ secrets.KUBE_CONFIG }}'
          overrule_existing_kubeconfig: "true"
      - uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade --install -f env/${{ inputs.env }}/values.yaml ${{ inputs.env }} ./env/${{ inputs.env }}
          kubeconfig: '${{ secrets.KUBE_CONFIG }}'
          overrule_existing_kubeconfig: "true"
