on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      directory:
        type: string
        default: .
      dockerfile:
        type: string
        default: Dockerfile
      buildargs:
        type: string
        required: false
    secrets:
      CR_PAT:
        required: true
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/third-place/${{ inputs.name }}:${{ github.sha }}
          build-args: ${{ inputs.buildargs }}
          file: ${{ inputs.dockerfile }}
