on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: ${{ github.repository }}
      directory:
        required: false
        type: string
        default: .
    secrets:
      CR_PAT:
        required: true
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - run: docker build -t ghcr.io/${{ inputs.name }}:${{ github.sha }} ${{ inputs.directory }}
      - run: docker push ghcr.io/${{ inputs.name }}:${{ github.sha }}
